### ISSUE TITLE
Needs an update?

### ISSUE THREAD

**Issue by bradstcroix** [AnnoyingTechnology/assetto-corsa-real-automatic-gearbox#1] opened 2024-08-16 10:56 UTC
Hi I was excited to find your fork of this app but I think now that AugGust's original version is no longer working with the latest CSP, this one may also be plagued with the same issue. I was unable to get it to show in the app menu while in game so never got to try it. An update would be fantastic if you're still wanting to keep this project current. Cheers

**Comment by AnnoyingTechnology** [comment] 2024-08-16 12:01
If CSP is acting up, try by unzipping, and placing the files manually in the proper folders. 

There is no reason for it not to work as it still works on my sim with files copied manually.

**Comment by bradstcroix** [comment] 2024-08-17 10:54
Thanks, the manual install method indeed worked and allows me to access the menu item now. Unfortunately it’s only working some of the time though - keeping the app on the screen the live data appears to pause often during which I can redline the car without it shifting up. It also seems to only upshift too, I can slow right down to a stop and it remains in high gear. Any thoughts on what else I can try? Many thanks

**Comment by AnnoyingTechnology** [comment] 2024-08-17 12:14
Could you do a video of that ? Seeing the behavior might give me some clues. 
Since upshifting works, have you double-checked that the shift down key is properly configured ? 
Are you using the "normal" mode ? Other modes are remains of the original code and likely won't work. 
Can you try to shift using the keys (P/O) on your keyboard to confirm ?

**Comment by bradstcroix** [comment] 2024-08-17 12:36
Thanks, yes I'll try and get a video together tomorrow. I did have another try with it since my last comment (after shutting CM down and starting again) and it indeed does downshift at very low rpm. The redline problem in 1st gear persists but I'll try to get that on the video. Can confirm the P and O mappings are working. I'm not sure what other modes there are apart from Manual and Auto in the plugin. The aggressiveness is at 1.5 which I note gears up at high rpm (about 7k) and downshifts down at at about 1.5k. Cheers

**Comment by AnnoyingTechnology** [comment] 2024-08-17 14:51
The aggressiveness not moving is odd, when you'll film the behavior please also film the aggressiveness. The only situation in which it should not move is when there is absolutely no action on the pedal for a long time or when coasting off throttle.

**Comment by bradstcroix** [comment] 2024-08-18 06:04
Ok here's a video, sorry for the large size.

https://www.dropbox.com/scl/fi/a2ui5cecz4vh4l53wb6x2/realauto.mp4?rlkey=8clah0hnatu7lcqpzzo2gy91h&dl=0

All gear changes apart from the initial shift to 1st are controlled by the app. You can see the redlining at the beginning and gears changing quickly after easing off the gas in 1st. The rest is just a combo of slowing down with less gas and braking on a couple of corners. Not sure where that weird shift to 5th at low rpm came from lol. The long slow part mid-lap is just coasting with no gas or brakes and then at the end braking again to try and make it shift down, which it eventually does at the end. 

Hope this helps give a bit more of a picture of what's happening. 

Thanks

**Comment by AnnoyingTechnology** [comment] 2024-08-18 06:17
None of what I saw in the video is normal.
My sim is kept offline as to avoid surprise forced updates, and I'm starting to think that the issue is due to a new version of AC or CM.

I'll try on a PC that's connected to internet with up-to-date AC/CM and see how it behaves there.

**Comment by AnnoyingTechnology** [comment] 2024-08-18 06:33
Just tried on a different computer with everything freshly installed (CM 0.8.2663.39678 (x86) .
* Installed the app using Drag & Drop on content manager (worked fine)
* Then settings as per the following screenshots.

![auto1](https://github.com/user-attachments/assets/5e6e2e0a-08a8-44a3-8e7a-6bccc7871eef)

![auto2](https://github.com/user-attachments/assets/736f6862-52d0-4af9-9bd0-89d2f61a4189)


And... everything works fine. headscratch.gif

**Comment by bradstcroix** [comment] 2024-08-18 06:39
Thanks for confirming on a fresh install. Well I’m stumped! Maybe I’ll try a different car and see I that makes a difference

**Comment by AnnoyingTechnology** [comment] 2024-08-18 06:44
I tested with the same 991 that you did, so that's not it. https://www.youtube.com/watch?v=6B7ti9roQq0

**Comment by bradstcroix** [comment] 2024-08-18 06:50
Argh if only mine would behave like that! That’s just what I’m looking to achieve

**Comment by AnnoyingTechnology** [comment] 2024-08-18 07:18
Well yeah, it's tuned to behave like a real gearbox ^^ 

Honestly I don't know what else could be wrong on your side, sorry. 

I checked regarding the two legacy modes, indeed don't show their name, it's always displayed as "normal". 
But only the first "normal" mode should be used. The one that has aggressiveness idling at 0.15 (not 0.5, and not 0.0). The one idling at 0.5 is the legacy "sport" and 0 is the legacy "eco".

**Comment by bradstcroix** [comment] 2024-08-18 07:43
Well thanks again for all your help so far. I’m going to mess around with a few things and maybe do a fresh install of CM. Glad to know the issue is on my end and not the app after all.

**Comment by bradstcroix** [comment] 2024-08-18 09:11
Ok after some more messing around I think the problem seems to be with the custom shaders patch version, as mentioned by the second guy in the comments here - https://www.overtake.gg/downloads/more-realistic-automatic-gearbox.33698/

I downgraded CSP to version 0.1.7.9 as a test and it's indeed behaving much more in line with your video from above. So it must be something blocking the python keyboard inputs that's been introduced in the latest CSP versions.

**Comment by AnnoyingTechnology** [comment] 2024-11-12 14:32
An update on this : the maintainers of CSP have [acknowledged the bug](https://github.com/ac-custom-shaders-patch/acc-extension-config/issues/501). They should hopefully fix it.

I'm closing the issue as it is out of my scope. Feel free to follow issue on CSP's repository instead.

**Closed as completed by AnnoyingTechnology** 2024-11-12 14:32 UTC
